AllCops:
  AllowSymlinksInCacheRootDirectory: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: 'indented'

Style/EmptyElse:
  EnforcedStyle: 'empty'

Style/EmptyMethod:
  EnforcedStyle: 'expanded'

# Our big numeric literals are Well-Known-Numbers, so don't worry too
# much...
Style/NumericLiterals:
  MinDigits: 6

# Probably mising sprintf or format would be fine, but pick one, and % is
# terrible.  We might culturally favor sprintf, but it looks like ruby
# likes format...
Style/FormatString:
  EnforcedStyle: 'format'

# This is a good idea in general, but hard to hardcode reasonably...
Layout/LineLength:
  Max: 125
  Exclude:
    - 'bin/pkg_fetch'
    - 'bin/pkg_glob'
    - 'bin/pkgdb'
    - 'bin/pkgdu'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'bin/portversion'
    - 'lib/pkgtools/pkgtools.rb'
    - 'tests/**/*'

# Similarly, lot of C programmers, so...
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: 'zero_only'

# There's a lot of garbage here, but forced anything isn't great, so deal
# with it manually as it comes up
Layout/ParameterAlignment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/RescueModifier:
  Enabled: false

# We'll probably never care about these
Style/CommentedKeyword:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/UnlessElse:
  Enabled: false

# This is a terrible idea
Style/StderrPuts:
  Enabled: false

# These are reasonable to ignore wholesale for now.  Maybe we'll revisit
# if we do a massive restyle...
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EvalWithLocation:
  Exclude:
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/portinfo.rb'
Style/GlobalVars:
  Enabled: false
Style/AccessModifierDeclarations:
  Exclude:
    - 'bin/portcvsweb'
    - 'lib/pkgtools/pkgdb.rb'

# It may be useful to enforce one way or another in the future
Style/SpecialGlobalVars:
  Enabled: false
  #EnforcedStyle: use_perl_names

# The things this caught in the existing codebase were all better written
# elsewise, so I'm leaving it enabled for now.  But it's a thing that
# could plausibly be used in proper code, so maybe we'll revisit...
Lint/LiteralAsCondition:
  Enabled: true

# It might be nice to have this more automaticly done, but forcing it
# always and everywhere to a single style (key vs table) is a terrible
# idea.
Layout/HashAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
# Further good-ish ideas, but forcing is terrible
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false

# This may be a good thing to change, but for now...
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/OneLineConditional:
  Exclude:
    - 'bin/portversion'

Style/PerlBackrefs:
  Exclude:
    - 'bin/pkg_glob'
    - 'bin/pkgdb'
    - 'bin/portcvsweb'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/pkgmisc.rb'
    - 'lib/pkgtools/pkgtools.rb'
    - 'lib/pkgtools/pkgversion.rb'
    - 'lib/pkgtools/portinfo.rb'
    - 'lib/pkgtools/portsdb.rb'

# This is probably a good idea, but it's a lot of work to phase in, so
# worry about it later.
Style/GuardClause:
  Exclude:
    - 'bin/pkgdb'
    - 'bin/portcvsweb'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'bin/portversion'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkgdbtools.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/pkgtools.rb'
    - 'lib/pkgtools/pkgversion.rb'
    - 'lib/pkgtools/portinfo.rb'
    - 'lib/pkgtools/portsdb.rb'

Style/Next:
  Exclude:
    - 'bin/pkg_glob'
    - 'bin/pkgdb'
    - 'bin/portcvsweb'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'lib/pkgtools/portsdb.rb'

Style/IfInsideElse:
  Exclude:
    - 'bin/pkgdb'
    - 'bin/portcvsweb'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkgtools.rb'

Style/MultilineBlockChain:
  Exclude:
    - 'lib/pkgtools/pkgdb.rb'

Style/MultilineTernaryOperator:
  Exclude:
    - 'bin/pkgdb'

Style/MutableConstant:
  Exclude:
    - 'bin/pkg_fetch'
    - 'bin/portcvsweb'
    - 'bin/portupgrade'
    - 'bin/portversion'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/pkgtools.rb'
    - 'lib/pkgtools/portinfo.rb'
    - 'lib/pkgtools/portsdb.rb'
    - 'tests/test_portinfo.rb'

# UNDECIDED: Not sure how we want to go with this...
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'bin/pkgdb'
    - 'bin/portupgrade'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkgdbtools.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/pkgmisc.rb'
    - 'lib/pkgtools/pkgtools.rb'
    - 'lib/pkgtools/portinfo.rb'
    - 'lib/pkgtools/portsdb.rb'

# Metrics are mostly stupid...
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# x-ref https://github.com/rubocop-hq/rubocop/issues/3696 on this
Lint/EmptyWhen:
  Exclude:
    - 'bin/pkgdb'
    - 'lib/pkgtools/pkgversion.rb'

# May be a better way to handle this, but for now...
Lint/SuppressedException:
  Exclude:
    - 'bin/pkg_fetch'
    - 'bin/portcvsweb'
Lint/UselessAccessModifier:
  Exclude:
    - 'bin/portcvsweb'

# Accept style guide, but leave legacy along
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'bin/portcvsweb'
Style/BarePercentLiterals:
  Exclude:
    - 'bin/pkgdu'
    - 'bin/portversion'

# Do seem to be wrong, and catching StandardError is probably fine, but
# I'm leaving alone for now.  Both uses are in loading config or the
# like, so...
Lint/RescueException:
  Exclude:
    - 'lib/pkgtools/pkgtools.rb'

# This is _probably_ OK?
Security/MarshalLoad:
  Exclude:
    - 'lib/pkgtools/pkgdbtools.rb'

inherit_from: .rubocop_todo.yml
