AllCops:
  AllowSymlinksInCacheRootDirectory: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: 'indented'

Style/EmptyElse:
  EnforcedStyle: 'empty'

Style/EmptyMethod:
  EnforcedStyle: 'expanded'

# Probably mising sprintf or format would be fine, but pick one, and % is
# terrible.  We might culturally favor sprintf, but it looks like ruby
# likes format...
Style/FormatString:
  EnforcedStyle: 'format'

# There's a lot of garbage here, but forced anything isn't great, so deal
# with it manually as it comes up
Layout/ParameterAlignment:
  Enabled: false

# We'll probably never care about these
Style/CommentedKeyword:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# These are reasonable to ignore wholesale for now.  Maybe we'll revisit
# if we do a massive restyle...
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EvalWithLocation:
  Exclude:
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/portinfo.rb'
Style/GlobalVars:
  Enabled: false

# It may be useful to enforce one way or another in the future
Style/SpecialGlobalVars:
  Enabled: false
  #EnforcedStyle: use_perl_names

# The things this caught in the existing codebase were all better written
# elsewise, so I'm leaving it enabled for now.  But it's a thing that
# could plausibly be used in proper code, so maybe we'll revisit...
Lint/LiteralAsCondition:
  Enabled: true

# It might be nice to have this more automaticly done, but forcing it
# always and everywhere to a single style (key vs table) is a terrible
# idea.
Layout/HashAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false

# This is probably a good idea, but it's a lot of work to phase in, so
# worry about it later.
Style/GuardClause:
  Exclude:
    - 'bin/pkgdb'
    - 'bin/portcvsweb'
    - 'bin/portsclean'
    - 'bin/portupgrade'
    - 'bin/portversion'
    - 'lib/pkgtools/pkgdb.rb'
    - 'lib/pkgtools/pkgdbtools.rb'
    - 'lib/pkgtools/pkginfo.rb'
    - 'lib/pkgtools/pkgtools.rb'
    - 'lib/pkgtools/pkgversion.rb'
    - 'lib/pkgtools/portinfo.rb'
    - 'lib/pkgtools/portsdb.rb'

# Metrics are mostly stupid...
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# x-ref https://github.com/rubocop-hq/rubocop/issues/3696 on this
Lint/EmptyWhen:
  Exclude:
    - 'bin/pkgdb'
    - 'lib/pkgtools/pkgversion.rb'

# May be a better way to handle this, but for now...
Lint/SuppressedException:
  Exclude:
    - 'bin/pkg_fetch'
    - 'bin/portcvsweb'
Lint/UselessAccessModifier:
  Exclude:
    - 'bin/portcvsweb'

# Accept style guide, but leave legacy along
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'bin/portcvsweb'
Style/BarePercentLiterals:
  Exclude:
    - 'bin/pkgdu'
    - 'bin/portversion'

# Do seem to be wrong, and catching StandardError is probably fine, but
# I'm leaving alone for now.  Both uses are in loading config or the
# like, so...
Lint/RescueException:
  Exclude:
    - 'lib/pkgtools/pkgtools.rb'

# This is _probably_ OK?
Security/MarshalLoad:
  Exclude:
    - 'lib/pkgtools/pkgdbtools.rb'

inherit_from: .rubocop_todo.yml
