AllCops:
  AllowSymlinksInCacheRootDirectory: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/Semicolon:
  AllowAsExpressionSeparator: true

# There's a lot of garbage here, but forced anything isn't great, so deal
# with it manually as it comes up
Layout/AlignParameters:
  Enabled: false

# We'll probably never care about these
Style/StringLiterals:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

# These are reasonable to ignore wholesale for now.  Maybe we'll revisit
# if we do a massive restyle...
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/RescueStandardError:
  Enabled: false

# It may be useful to enforce one way or another in the future
Style/SpecialGlobalVars:
  Enabled: false
  #EnforcedStyle: use_perl_names

# It might be nice to have this more automaticly done, but forcing it
# always and everywhere to a single style (key vs table) is a terrible
# idea.
Layout/AlignHash:
  Enabled: false

inherit_from: .rubocop_todo.yml
