AllCops:
  AllowSymlinksInCacheRootDirectory: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/Semicolon:
  AllowAsExpressionSeparator: true

# We'll probably never care about these
Style/StringLiterals:
  Enabled: false

# These are reasonable to ignore wholesale for now.  Maybe we'll revisit
# if we do a massive restyle...
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/RescueStandardError:
  Enabled: false

# It may be useful to enforce one way or another in the future
Style/SpecialGlobalVars:
  Enabled: false
  #EnforcedStyle: use_perl_names

# It might be nice to have this more automatic, but forcing it always and
# everywhere is probably a terrible idea.
Layout/AlignHash:
  Enabled: false

inherit_from: .rubocop_todo.yml
